import jsPDF from "jspdf";
import { PredictionResult } from "./types";
import { formatDateTime, formatPercent } from "./utils";

async function imageUrlToDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(url);
    const blob = await res.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export async function downloadPredictionPdf(result: PredictionResult) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("MedScan AI — Diagnostic Report", margin, y);
  y += 28;

  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 24;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const rows: [string, string][] = [
    ["Patient", result.patientName],
    ["Modality", result.modality],
    ["Finding", result.finding],
    ["Confidence", formatPercent(result.confidence)],
    ["Model version", result.modelVersion],
    ["Inference time", `${result.inferenceMs}ms`],
    ["Read at", formatDateTime(result.createdAt)],
  ];
  for (const [label, value] of rows) {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, margin + 130, y);
    y += 20;
  }
  y += 8;

  const imgData = await imageUrlToDataUrl(result.imageUrl);
  if (imgData) {
    const imgSize = 200;
    doc.setFont("helvetica", "bold");
    doc.text("Scan", margin, y);
    y += 10;
    try {
      doc.addImage(imgData, "JPEG", margin, y, imgSize, imgSize);
    } catch {
      try {
        doc.addImage(imgData, "PNG", margin, y, imgSize, imgSize);
      } catch {
        // skip the image rather than break the whole PDF
      }
    }
    y += imgSize + 24;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Probability breakdown", margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  for (const p of result.probabilities) {
    doc.text(p.label, margin, y);
    doc.text(formatPercent(p.probability), margin + 300, y);
    y += 18;
  }
  y += 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Clinical notes", margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const noteLines = doc.splitTextToSize(result.notes, pageWidth - margin * 2);
  doc.text(noteLines, margin, y);
  y += noteLines.length * 14 + 20;

  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text(
    "Generated by MedScan AI. This is an AI-assisted read and does not replace clinical judgment.",
    margin,
    doc.internal.pageSize.getHeight() - 30
  );

  const filename = `medscan-${result.patientName.replace(/\s+/g, "-").toLowerCase()}-${result.id}.pdf`;
  doc.save(filename);
}